name: CI
on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'yarn'
      - run: yarn install
  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: yarn build
  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: yarn test
